export default[
    {
        name:"shujuchakanbaobiao",
        label:"数据查看报表"
    },
    {
        name:"spcfenxibaobiao",
        label:"test"
    },
    {
        name:"location",
        label:"位置"
    },
    {
        name:"off",
        label:"关机"
    },
    {
        name:"function",
        label:"功能"
    },
    {
        name:"process",
        label:"工序能力报表"
    },
    {
        name:"product",
        label:"产品"
    },
    {
        name:"runaway",
        label:"失控点报表"
    },
    {
        name:"unqualified",
        label:"不合格数报表"
    },
    {
        name:"text",
        label:"文本"
    },
    {
        name:"riqi",
        label:"日期"
    },
    {
        name:"about",
        label:"关于"
    },
    {
        name:"collection",
        label:"采集"
    },
    {
        name:"report",
        label:"报表"
    },
    {
        name:"chanpinguanli",
        label:"产品管理"
    },
    {
        name:"fuwushili",
        label:"服务实例"
    },
    {
        name:"yilaiguanxi",
        label:"依赖关系"
    },
    {
        name:"wendangshezhi",
        label:"文档设置"
    },
    {
        name:"qingqiugenzongrizhi",
        label:"请求跟踪日志"
    },

    {
        name:"fuwugaikuang",
        label:"服务概况"
    },
    {
        name:"canshupeizhi",
        label:"参数配置"
    },
    {
        name:"cuowubaogao",
        label:"错误报告"
    },
    {
        name:"zhongjianjian",
        label:"中间件"
    },
    {
        name:"jiagouguanli",
        label:"架构管理"
    },
    
    {
        name:"huanjingguanli",
        label:"环境管理"
    },
    {
        name:"fuwushouquan",
        label:"服务授权"
    },
    {
        name:"renyuanguanli",
        label:"人员管理"
    },
    {
        name:"xiangmuguanli",
        label:"项目管理"
    },
    {
        name:"fuwushezhi",
        label:"服务设置"
    },
    {
        name:"fuwuguanli",
        label:"服务管理"
    },
    {
        name:"bangzhu",
        label:"帮助"
    },

    {
        name:"zhiliangguanli",
        label:"质量管理"
    },
    {
        name:"baojing",
        label:"报警"
    },
    {
        name:"guanyu",
        label:"关于"
    },
    {
        name:"gongyiguanli",
        label:"工艺管理"
    },
    {
        name:"gongyinglianguanli",
        label:"供应链管理"
    },
    {
        name:"shengchanguanli",
        label:"生产管理"
    },
    {
        name:"moxingguanli",
        label:"模型管理"
    },
    {
        name:"shebeiguanli",
        label:"设备管理"
    },
    {
        name:"xitongshezhi",
        label:"系统设置"
    },

    {
        name:"lingdaojiashicang",
        label:"领导驾驶舱"
    },
    {
        name:"yuanshujupeizhi",
        label:"元数据配置"
    },
    {
        name:"jiankong",
        label:"监控"
    },
    {
        name:"shujuku",
        label:"数据库"
    },
    {
        name:"yunhangshipeizhi",
        label:"运行时配置"
    },
]